name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag krokodile888/dogcat:latest
    - name: Push the Docker image
      run: docker login -u krokodile888 -p ${{ secrets.DOCKER_TOKEN }} && docker push krokodile888/dogcat:latest
    - name: Copy file to the repository
      run: docker run --rm -d -v ~/krokodile888/dogcat/log:/log -v ~/krokodile888/dogcat/data:/data --name dogcat krokodile888/dogcat:latest
